---
version: 2
registries:
  vertx-dagger-bom:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/BenSlabbert/vertx-dagger-bom"
    username: "BenSlabbert"
    password: "${{ secrets.GH_TOKEN }}"
  git-version-extension:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/BenSlabbert/git-version-extension"
    username: "BenSlabbert"
    password: "${{ secrets.GH_TOKEN }}"
  vertx-dagger-codegen:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/BenSlabbert/vertx-dagger-codegen"
    username: "BenSlabbert"
    password: "${{ secrets.GH_TOKEN }}"
  vertx-dagger-commons:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/BenSlabbert/vertx-dagger-commons"
    username: "BenSlabbert"
    password: "${{ secrets.GH_TOKEN }}"
  tx-manager:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/BenSlabbert/tx-manager"
    username: "BenSlabbert"
    password: "${{ secrets.GH_TOKEN }}"
  vertx-dagger-app-api:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/BenSlabbert/vertx-dagger-app-api"
    username: "BenSlabbert"
    password: "${{ secrets.GH_TOKEN }}"
  vertx-dagger-starter:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/BenSlabbert/vertx-dagger-starter"
    username: "BenSlabbert"
    password: "${{ secrets.GH_TOKEN }}"
  svelte-ui-lib:
    type: "npm-registry"
    url: "https://maven.pkg.github.com/BenSlabbert/vertx-dagger-ui-lib"
    username: "BenSlabbert"
    password: "${{ secrets.GH_TOKEN }}"
  vertx-json-writer:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/BenSlabbert/vertx-json-writer"
    username: "BenSlabbert"
    password: "${{ secrets.GH_TOKEN }}"
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  registries:
  - "vertx-dagger-bom"
  - "git-version-extension"
  - "vertx-dagger-codegen"
  - "vertx-dagger-commons"
  - "vertx-dagger-starter"
  - "vertx-dagger-app-api"
  - "tx-manager"
  - "vertx-json-writer"
  labels:
  - "dependencies"
  - "automerge"
  groups:
    updates:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: "npm"
  directory: "/frontend/app"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  registries:
  - "svelte-ui-lib"
  labels:
  - "dependencies"
  - "automerge"
  groups:
    updates:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: "npm"
  directory: "/jte-htmx-parent/frontend/app"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  registries:
  - "svelte-ui-lib"
  labels:
  - "dependencies"
  - "automerge"
  groups:
    updates:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  labels:
  - "dependencies"
  - "automerge"
  groups:
    updates:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
