---
version: "3"
services:
  iam-jvm:
    hostname: "iam"
    image: "iam:jvm-latest"
    ports:
    - "8080:8080"
    - "50051:50051"
    volumes:
    - "./docker-config.json:/config.json"
    command:
    - "/config.json"
    depends_on:
    - "redis"
  iam-native:
    hostname: "iam"
    image: "iam:native-latest"
    ports:
    - "8080:8080"
    - "50051:50051"
    volumes:
    - "./docker-config.json:/config.json"
    command:
    - "/config.json"
    depends_on:
    - "redis"
  catalog-jvm:
    hostname: "catalog"
    image: "catalog:jvm-latest"
    environment:
      SEED: "true"
    ports:
    - "8081:8080"
    volumes:
    - "./docker-config.json:/config.json"
    command:
    - "/config.json"
    depends_on:
    - "redis"
  catalog-native:
    hostname: "catalog"
    image: "catalog:native-latest"
    environment:
      SEED: "true"
    ports:
    - "8081:8080"
    volumes:
    - "./docker-config.json:/config.json"
    command:
    - "/config.json"
    depends_on:
    - "redis"
